modLoader="javafml"
loaderVersion="[45,)"
license="LGPLv3"
[[mods]]
modId="sussyballs"
version="${file.jarVersion}"
displayName="Sussy Balls"
logoFile="sussyballs.png"
credits="LudoCrypt"
authors="LudoCrypt"

description='''
Craft Suspicious Snowballs using the ingredients from Suspicious Stews!

Logo made by nekomaster1000 & LudoCrypt
Texture by Aux
uk_ua - UnRoman
it-it - 5imGitHub
'''

[[dependencies.sussyballs]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sussyballs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
